package domain.company;

public enum Permissions {
    MANAGE_EVENTS_INVENTORY,
    DEFINE_VENUE_MAP,
    MANAGE_POLICIES,
    RESPOND_TO_INQUIRIES,
    VIEW_PURCHASE_HISTORY,
    GENERATE_SALES_REPORTS
}