package domain.dataType;

public enum PermissionType {
    MANAGE_EVENTS_INVENTORY,
    MANAGE_POLICIES,
    RESPOND_TO_INQUIRIES,
    VIEW_PURCHASE_HISTORY,
    GENERATE_SALES_REPORTS,
    CREATE_EVENT,
    VIEW_ORDERS_HISTORY,
    VIEW_CLOSED_COMPANIES,
    DELETE_EVENT
}
