package DTO;
public enum NotifyType {
    GENERAL_POPUP,
    QUEUE_EVENT_TURN_ARRIVED,
    QUEUE_WEB_TURN_ARRIVED,
    KICKOUT_TAB_NAVIGATION,
    ROLE_APPOINTMENT_REQUEST,
    TOKEN_EXPIRED,
    ACCOUNT_REMOVED
}
